import type { Metadata } from 'next';
import './globals.scss';
import '../styles/navbar.scss';
import '../styles/header.scss';
import '../styles/results.scss';
import '../styles/services.scss';

export const metadata: Metadata = {
    title: 'SEO SaaS Company',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    );
}
