import LenisProvider from '@/components/LenisProvider';
import type { Metadata } from 'next';
import './globals.scss';
import '../styles/navbar.scss';
import '../styles/header.scss';
import '../styles/results.scss';
import '../styles/services.scss';
import '../styles/getStarted.scss';
import '../styles/pricing.scss';
import '../styles/testimonials.scss';
import '../styles/companyInNumbers.scss';
import '../styles/Faq.scss';
import '../styles/footer.scss';
import IntroScreen from '@/components/IntroScreen';

export const metadata: Metadata = {
    title: 'SEO SaaS Company',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <LenisProvider />
            <body>
                <IntroScreen />
                {children}
            </body>
        </html>
    );
}
